[build]
  base = "faranz"
  command = "hugo"
  publish = "faranz/public"

[build.environment]
  HUGO_VERSION = "0.111.3"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --buildFuture --buildDrafts"
